swoole/swoole-cli

prepare.php

Fix https://github.com/swoole/swoole-cli/issues/14

fix: link mimalloc

---

sapi/make.php

变更：
1.  配置阶段 允许使用使用的多行字符串
1.  配置阶段 添加配置错误检测
1.  make 和 make install 阶段添加构建检测
最终效果：

配置阶段允许编写多行字符串；make 和 make install 阶段添加构建检测

---

bin/LICENSE
composer.lock
conf.d/curl.php
conf.d/gd.php
conf.d/gmp.php
conf.d/imagick.php
conf.d/intl.php
conf.d/mbstring.php
conf.d/mongodb.php
conf.d/openssl.php
conf.d/sodium.php
conf.d/sqlite3.php
conf.d/xml.php
conf.d/xsl.php
conf.d/zip.php
conf.d/zlib.php
sapi/make.php

1.  修改依赖库安装目录；
1.  调整依赖库安装顺序；
1.  确认各库pkg-config支持情况
1.  libgif 库安装修改
检测pkg-config 支持情况，如下这三个库不支持 pkg-config 
1.  libiconv
1.  bzip2
1.  libgif

修改依赖库安装目录；调整依赖库安装顺序；确认各库pkg-config支持情况

---

sapi/Preprocessor.php
sapi/credits.php

类似chromium 浏览器：
```url
chrome://credits/
```
展示的信息

生成开源组件或工具的列表

---

conf.d/bison.php
sapi/Preprocessor.php
sapi/constants.php
sapi/make.php

生成如下配置
```bash
export PATH=/usr/bison/bin:/usr/pgsql/bin:/usr/libxml2/bin:$PATH
```
安装依赖库时，需要通过检测： 比如  pg_config ，  icu-config  ， xml2-config ， xslt-config

环境变量PATH添加自定义路径

---

conf.d/xlswriter.php
sapi/constants.php

暂不合并，等待这个PR  https://github.com/swoole/swoole-cli/pull/44  完成

添加libxlswriter库和xlswriter扩展 

---

conf.d/curl.php

curl 启用libcares库

---

conf.d/gd.php
sapi/constants.php

指定 libjpeg libgif libzip zlib bzip2 安装目录

---

conf.d/imagick.php

合并本依赖库之前，需要先解决，freetype 对于 brotli 依赖库的问题

解决 imagemagick 安装问题，主要内容：禁用非指定的依赖库

---

conf.d/zip.php
conf.d/zstd.php

libzip 启用默认依赖库 openssl zlib bzip2 liblzma libzstd

libzip 启用默认依赖库 openssl zlib bzip2 liblzma libzstd

---

conf.d/gd.php
conf.d/swoole.php
conf.d/zip.php
conf.d/zstd.php

freetype 启用依赖库 brotli
依赖 https://github.com/swoole/swoole-cli/pull/65

freetype 启用依赖库 brotli

---

conf.d/curl.php

curl 启用 brotli 库

---

conf.d/curl.php

curl 启用 libzstd
依赖：https://github.com/swoole/swoole-cli/pull/68/files

curl 启用 libzstd

---

sapi/Preprocessor.php
sapi/make.php

完善make_config，实现按需启用扩展以及依赖库

---

sapi/Preprocessor.php
sapi/make.php

优化make_config

---

conf.d/gmp.php
conf.d/mongodb.php
sapi/make.php

解决 gmp 生成动态链接库 和 mongodb 链接系统库的问题

解决 gmp 生成动态链接库 和 mongodb 链接系统库的问题

---

conf.d/intl.php
sapi/unit/MainTest.php

为安装 依赖库ICU 添加单元测试

---

composer.lock
conf.d/imagick.php
sapi/Preprocessor.php
sapi/constants.php
sapi/make.php

测试 md5 验证文件内容完整 例子：
```text
library:    imagemagick   md5sum       `37b896e9eecd379a6cd0d6359b9f525a
extension:  imagick       md5sum       `f7b5e9b23fb844e5eb035203d316bc63`
```
验证md5 例子
```bash
echo '11111111111111111' > /work/pool/ext/imagick-3.6.0.tgz
echo '11111111111111111' > /work/pool/lib/ImageMagick-v7.1.0-62.tar.gz
```

wget 下载添加重试机制 ；格式化批量下载功能的代码

---

README.md
docs/Cygwin.md

增加Cygwin下pgsql编译说明 & fix typo

---

conf.d/curl.php
sapi/constants.php
sapi/unit/MainTest.php

测试： 
```bash 
bin/swoole-cli vendor/bin/phpunit sapi/unit/MainTest.php
```

curl 启用 libssh2

---

conf.d/gd.php

为了解决链接动态库问题，顺便把libjpeg库目录也解决了

---

conf.d/openssl.php

为升级到 openssl v3 做准备

---

conf.d/curl.php
docs/macOS.md

修复停用libidn2 遗漏的配置

---

sapi/scripts/cygwin-pack.php
sapi/scripts/install-cygwin.sh

fix cygwin pack

---

.github/workflows/macos-x86_64-build.yml
sapi/download-box/README.md
sapi/multistage-build-dependencies-container/README.md
sapi/multistage-build-dependencies-container/all-dependencies-build-container.sh
sapi/multistage-build-dependencies-container/all-dependencies-build-init.sh
sapi/quickstart/setup-php-runtime.sh

github action macos build

---

sapi/download-box/README.md
sapi/download-box/download-box-build.sh
sapi/download-box/download-box-get-archive-from-container.sh
sapi/download-box/download-box-init.sh
sapi/download-box/download-box-server-run.sh
sapi/quickstart/README.md
sapi/quickstart/linux/README.md
sapi/quickstart/linux/extra/README.md
sapi/quickstart/setup-php-runtime.sh

Fix download box

---

.github/workflows/linux-aarch64.yml
.github/workflows/macos-x86_64-build.yml
sapi/download-box/download-box-get-archive-from-container.sh
sapi/download-box/download-box-get-archive-from-server.sh
sapi/download-box/download-box-init.sh
sapi/download-box/download-box-server-run.sh
sapi/quickstart/README.md
sapi/quickstart/linux/README.md
sapi/quickstart/linux/arm64/README.md
sapi/quickstart/linux/extra/README.md
sapi/quickstart/setup-php-runtime.sh

添加 linux aarch64 build

---

docs/macOS.md
sapi/quickstart/enable-single-extension-example.sh
sapi/scripts/enable-single-extension.sh
sapi/src/DownloadBoxTrait.php
sapi/src/Extension.php
sapi/src/Preprocessor.php
sapi/src/builder/extension/event.php
sapi/src/builder/extension/igbinary.php
sapi/src/builder/extension/mongodb.php
sapi/src/builder/extension/pdo_mysql.php
sapi/src/builder/extension/pdo_odbc.php
sapi/src/builder/extension/pdo_pgsql.php
sapi/src/builder/extension/pdo_sqlite.php
sapi/src/builder/extension/pgsql.php
sapi/src/builder/extension/swoole.php
sapi/src/builder/library/libevent.php
sapi/src/builder/library/libsasl.php
sapi/src/builder/library/pgsql.php
sapi/src/builder/library/snappy.php
sapi/src/builder/library/unixodbc.php
sapi/src/constants.php

启用扩展pgsql  pdo_pgsql  event 
swoole 扩展启用 pgsql
添加库： pgsql libevent   unixodbc  snappy(暂不可用）  libsasl（暂不可用）

Experiment dev 2023 05 24

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64-latest-swoole.yml
.github/workflows/macos-x86_64.yml
sapi/download-box/download-box-get-archive-from-container.sh

Build native php

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-x86_64.yml
.github/workflows/windows-cygwin.yml
sapi/scripts/cygwin/cygwin-config-ext.sh

更新 拉取swoole 源码方式

---

.github/workflows/mirror-to-gitee.yml

添加同步到gitee action

---

README.md
prepare.php

更新 指定PHP 版本

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-x86_64.yml
prepare.php
sapi/quickstart/mark-install-library-cached.sh
sapi/src/builder/library/pgsql.php

添加预安装命令，用于构建前准备必要的组件

---

.gitignore
sapi/src/Preprocessor.php
sapi/src/template/make-install-deps.php
sapi/src/template/make_init.php

更新 预安装命令，准备构建环境

---

sapi/src/Library.php
sapi/src/Preprocessor.php
sapi/src/Project.php
sapi/src/builder/extension/swoole_git.php
sapi/src/builder/extension/swoole_latest.php
sapi/src/builder/library/pgsql.php
sapi/src/template/make.php

1. 实现： 及时更新 ext/swoole 的源代码
2. pgsql 导入变量  LIBPQ_CFLAGS   LIBPQ_LIBS

及时更新 ext/swoole 的源代码 和PGSQL 添加导入变量

---

sapi/src/template/make.php

fix bug on with-build-type=dev

---

sapi/extension-dependency-graph/generate-dependency-graph.sh
sapi/src/builder/extension/aaa_example.php
sapi/src/builder/library/aaa_example.php
sapi/src/constants.php

添加 新增扩展例子，新增依赖库例子

---

sapi/src/builder/extension/aaa_example.php
sapi/src/builder/library/aaa_example.php

更新 添加  扩展 、静态依赖库 的例子

---

sapi/src/builder/extension/aaa_example.php
sapi/src/builder/library/aaa_example.php

更新 添加静态链接库 例子

---

sapi/quickstart/linux/alpine-init.sh
sapi/quickstart/linux/debian-init.sh
sapi/src/builder/library/libedit.php
sapi/src/builder/library/unixODBC.php
sapi/src/builder/library/zlib.php
sapi/src/template/make.php

改进unixODBC  libedit 构建静态链接库

---

sapi/src/builder/library/dav1d.php
sapi/src/builder/library/pgsql.php
sapi/src/builder/library/sdl2.php

优化 pgsql 、 SDL2 、dav1d 构建代码

---

sapi/quickstart/linux/debian-init.sh
sapi/src/builder/extension/swoole_latest.php

swoole_latest add extenson dependency

swoole_latest add extenson dependency

---

sapi/quickstart/linux/alpine-init.sh
sapi/quickstart/linux/debian-init.sh
sapi/src/Library.php
sapi/src/Preprocessor.php
sapi/src/Project.php
sapi/src/builder/library/bzip2.php
sapi/src/builder/library/libiconv.php
sapi/src/template/make.php

配置  git:// 协议可使用代理

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-x86_64.yml
prepare.php
sapi/quickstart/clean-no-match-library-for-php.sh
sapi/quickstart/mark-install-library-cached.sh
sapi/src/builder/extension/openssl.php
sapi/src/template/make-env.php
sapi/src/template/make.php

支持 类似 php-8.3.0beta2 版本的构建

---

prepare.php
sapi/src/builder/library/libssh2.php

upgrade libssh2 version to 1.11.0

upgrade libssh2 version to 1.11.0

---

prepare.php
sapi/src/builder/extension/swoole.php
sapi/src/builder/extension/swow.php
sapi/src/template/make-export-variables.php
sapi/src/template/make.php

1、swoole 、swow 每次构建自动清空构建缓存
2、默认启用构建安装缓存

默认启用构建安装缓存

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-x86_64.yml
sapi/src/Preprocessor.php
sapi/src/builder/extension/gd.php
sapi/src/builder/extension/swoole.php

swoole upgrade to v5.1.0

---

sapi/src/template/make.php

Experiment 修改库缓存设置

---

sapi/quickstart/prepare-example.sh
sapi/quickstart/setup-php-runtime-in-docker.sh
sapi/quickstart/setup-php-runtime.sh
sapi/src/Library.php
sapi/src/builder/library/openssl.php
sapi/src/template/make.php

更新构建库 缓存配置

---

sapi/quickstart/build-example.sh
sapi/quickstart/clean-folder.sh
sapi/quickstart/prepare-example.sh
sapi/quickstart/setup-php-runtime-in-docker.sh
sapi/quickstart/setup-php-runtime.sh
sapi/src/builder/library/php_src.php
sapi/src/template/make.php

update make.php 和添加一键构建命令

---

sapi/quickstart/clean-no-match-library-for-php.sh

添加脚本，清除无效的链接库缓存，重新构建新的链接库

---

prepare.php
sapi/quickstart/clean-folder.sh
sapi/quickstart/linux/run-alpine-container-full.sh
sapi/src/builder/library/php.php

使用 /dev/shm 目录加速构建

---

build-release-example.sh

fix build-release-example.sh bug

fix build-release-example.sh bug 

---

.github/workflows/linux-aarch64.yml
sapi/download-box/web-server.php
sapi/multistage-build-dependencies-container/Dockerfile-all-dependencies-alpine
sapi/multistage-build-dependencies-container/all-dependencies-build-container.sh
sapi/quickstart/linux/arm64/run-qemu-user-static.sh
sapi/quickstart/linux/run-alpine-container.sh

完善github action aarch64 配置

---

sapi/src/builder/library/libwebp.php

info: https://security-tracker.debian.org/tracker/CVE-2023-4863

upgrade libwebp to v1.3.2,  fix CVE-2023-4863

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-x86_64.yml
.gitignore
prepare.php
sapi/quickstart/mark-install-library-cached.sh
sapi/src/Library.php
sapi/src/Preprocessor.php
sapi/src/Project.php
sapi/src/template/make.php

配置缓存移动到  /usr/local/swoole-cli/library_name/.cached

Feature install library cache

---

sapi/download-box/download-box-get-archive-from-container.sh
sapi/download-box/download-box-get-archive-from-server.sh
sapi/src/Preprocessor.php

使用缓存解决 github action  对 gmplib.org 频繁下载资源的问题

使用缓存解决 github action  频繁 对 gmplib.org 下载资源的问题

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-x86_64.yml
build-release-example.sh

修复 github action composer 环境配置错误 
update build-release-example.sh

update action config and update example

---

docs/Cygwin.md

update cygwin doc

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-x86_64.yml
build-release-example.sh

change download-mirror-url

---

sapi/quickstart/clean-no-match-library-for-php.sh

与主分支容器保持一致

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-x86_64.yml

update github action cache config

update github action cache config 

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-x86_64.yml
build-release-example.sh
docs/options.md
sapi/docker/Dockerfile
sapi/docker/Dockerfile-arm64
sapi/download-box/README.md
sapi/download-box/download-box-batch-downloader.sh
sapi/download-box/download-box-get-archive-from-container.sh
sapi/download-box/download-box-get-archive-from-server.sh
sapi/download-box/download-box-init.sh
sapi/multistage-build-dependencies-container/README.md
sapi/multistage-build-dependencies-container/all-dependencies-run-container-test.sh
sapi/quickstart/README.md
sapi/quickstart/linux/debian-init.sh
sapi/quickstart/linux/run-alpine-container-full.sh
sapi/quickstart/macos/macos-init.sh
sapi/src/builder/library/gmp.php
sapi/src/builder/library/libwebp.php
sapi/src/builder/library/pgsql.php
sapi/src/template/make.php

1、修复 quick start 脚本bug
2、pgsql 添加导入变量

Fix clean cache

---

.github/workflows/mirror-to-gitee.yml

允许其它分支 同步到gitee

---

.github/workflows/windows-cygwin.yml
sapi/src/builder/extension/swoole.php

优化 macos worfkow conf

---

sapi/quickstart/linux/connection-swoole-cli-rhel.sh
sapi/quickstart/linux/rhel-init.sh
sapi/quickstart/linux/run-rhel-container.sh
sapi/src/builder/library/libavif.php
sapi/src/constants.php

增加 rhel 容器构建环境

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-x86_64.yml
.github/workflows/windows-cygwin.yml

Feature update workflow config

---

sapi/quickstart/linux/alpine-init.sh
sapi/quickstart/linux/debian-init.sh

1、解决debian-init.sh 脚本 bug 
1、更新脚本 ,保持与  build_native_php 分支一致
1、alpine 去除 限速的 镜像站点

fix debian-init.sh script bug 

---

sapi/quickstart/setup-php-runtime.sh
setup-php-runtime.sh

setup-php-runtime.sh 允许使用 socks5h 协议

setup-php-runtime.sh 允许使用 socks5h 协议

---

sapi/multistage-build-dependencies-container/Dockerfile-all-dependencies-alpine
sapi/multistage-build-dependencies-container/README.md
sapi/multistage-build-dependencies-container/all-dependencies-build-container.sh

Fix build dependencies container

Fix build dependencies container

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-x86_64.yml

release remove debug archive

---

docs/extensions.md
sapi/src/builder/extension/mailparse.php

https://github.com/swoole/swoole-src/issues/5381

add extension mailparse

---

sapi/src/builder/library/pgsql.php

https://github.com/Homebrew/homebrew-core/issues/155651#issuecomment-1828251512
https://www.postgresql.org/message-id/CXA1532Q80DK.81UOGP3O5AP6%40neon.tech

upgrade pgsql to 16.3

---

sapi/src/builder/library/unix_odbc.php

fix unixodbc build error

---

README.md
setup-swoole-cli-runtime.sh

实现 快速 下载 swoole-cli 运行时
一条下载命令，即可使用 swoole-cli

add download swoole-cli script

---

.github/workflows/linux-x86_64.yml

disable swoolg pg test

---

.github/workflows/linux-aarch64.yml
.github/workflows/linux-x86_64.yml
.github/workflows/macos-aarch64.yml
.github/workflows/macos-x86_64.yml
.github/workflows/windows-cygwin.yml
prepare.php

详见： https://github.com/swoole/swoole-cli/releases/tag/v5.1.5.0

set swoole version v5.1.5 解决发版问题 

---

sapi/src/builder/enabled_extensions.php

xslwriter 扩展 源码：https://github.com/viest/php-ext-xlswriter/releases

默认启用xslwriter 扩展

---

sapi/docker/build-export-container.sh
sapi/quickstart/linux/run-alpine-container.sh
sapi/quickstart/linux/run-debian-container.sh
sapi/src/template/make.php

AtomHub 已下线，移除开放原子容器镜像

---

sapi/scripts/build-swoole-cli-alpine-container.sh

结果类似： 
https://hub.docker.com/repository/docker/jingjingxyk/swoole-cli/tags

添加生成 docker.io/phpswoole/swoole-cli 容器 脚本

---

docs/upgrade.md
sapi/scripts/download-php-src-archive.php
sync-source-code.php

执行结果变更； https://github.com/jingjingxyk/swoole-cli/pull/188/files

优化 同步 php 源码
